### ISSUE TITLE
No support for special "iterable" type

### ISSUE THREAD

**Issue by bug-tape** [sebastianbergmann/type#2]
Newest PHPUnit version 8.2.0 gives us a lot of warnings ("Method ... may not return value of type array") when mocking methods which have "iterable" as return type hint and giving arrays as return value.

Perhaps this should be its own Type-Class here?

**Comment by bug-tape** [comment]
Similar problem with "callable"

**Comment by sebastianbergmann** [comment]
Should be fixed by https://github.com/sebastianbergmann/type/commit/3f27e78bad35a7f29ed6d13b73eaab9f6b6acadb and https://github.com/sebastianbergmann/type/commit/79fd7f2f8acff994d4a330bb434b09b813479068, respectively.
