### ISSUE TITLE
Check Type::isAssignable() implementations with regard to nullability

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/type#23]
@stof [wrote](https://github.com/sebastianbergmann/type/commit/b99795cb82621dfd202a59b683f36510db8885eb#r71094216):
> 2 types allowing null are not automatically assignable to each other. Null is assignable to a type allowing null. And a type allowing null is not assignable to a type not allowing null. But `?string` is not assignable to `?int`

**Comment by stof** [comment]
Btw, infection pushing you to perform such changes and the testsuite accepting it seems to indicate that the test coverable of `isAssignable` is incomplete.

**Comment by sebastianbergmann** [comment]
The changes that were prompted by Infection have been reverted. The `isAssignable()` implementation are now as they were. They likely still need more tests, but I'm closing this ticket now.
